# application.properties
spring.application.name=api_conexao_parking

# Define que o perfil 'dev' é o padrão se você não avisar nada
spring.profiles.active=dev

# Configurações comuns a ambos
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never

admin.email=vini@adm.com
admin.password=admin123