spring.application.name=api_conexao_parking
spring.profiles.active=dev
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never
admin.email=vini@adm.com
admin.password=admin123
api.security.token.secret=${JWT_SECRET:secret-default-32-chars-minimo}