# application-prod.properties
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

api.security.token.secret=${JWT_SECRET}
server.port=${PORT:8080}

# No Railway, geralmente não queremos ver o SQL no log por performance
spring.jpa.show-sql=false