spring.application.name=api_conexao_parking
server.port=${PORT:8080}


spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.flyway.url=${MYSQL_URL}
spring.flyway.user=${MYSQLUSER}
spring.flyway.password=${MYSQLPASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update