spring.application.name=api_conexao_parking
spring.profles.active=dev
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never
admin.email=vini@adm.com
admin.password=admin123